[package]
name = "mydata"
version = "0.1.0"
edition = "2024"

[dependencies]
iced = "0.12"
wgpu = "0.15"
chrono ={ version = "0.4.41",features = ["serde"] } 
serde = { version = "1.0.219" ,features = ["derive"] }
serde_json = "1.0"